# Generated by Django 5.2.12 on 2026-03-29 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=120)),
                ('sous_titre', models.CharField(blank=True, max_length=220)),
                ('texte_bouton', models.CharField(blank=True, default='Découvrir', max_length=50)),
                ('lien', models.CharField(blank=True, help_text='URL ou ancre (#catalogue)', max_length=255)),
                ('image', models.ImageField(help_text='Résolution recommandée : 1600 × 700 px', upload_to='slider/')),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Slide',
                'verbose_name_plural': 'Slides',
                'ordering': ['ordre', 'created_at'],
            },
        ),
    ]
